name: Pull Request
description: Submit a pull request with time tracking
title: "[PR]: "
labels: ["needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this pull request!
  
  - type: input
    id: related-issue
    attributes:
      label: Related Issue
      description: Please link the issue this PR addresses
      placeholder: "e.g., #123"
    validations:
      required: true
      
  - type: input
    id: story-points
    attributes:
      label: Story Points
      description: How many story points were allocated to this task(one story point is one hour)?
      placeholder: "e.g., 3"
    validations:
      required: true
      
  - type: dropdown
    id: change-type
    attributes:
      label: Type of Change
      description: What kind of change does this PR introduce?
      multiple: true
      options:
        - Bug fix
        - New feature
        - Breaking change
        - Documentation update
        - Performance improvement
        - Refactoring
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a brief description of the changes
      placeholder: Explain the changes you've made...
    validations:
      required: true
      
  - type: textarea
    id: testing
    attributes:
      label: Testing Performed
      description: Describe the tests you've performed
      placeholder: Explain how you tested these changes...
    validations:
      required: true
      
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Before submitting this PR, please make sure:
      options:
        - label: My code follows the project's style guidelines
          required: true
        - label: I have performed a self-review of my code
          required: true
        - label: I have commented my code, particularly in hard-to-understand areas
          required: false
        - label: I have made corresponding changes to the documentation
          required: false
        - label: My changes generate no new warnings
          required: true
        - label: I have added tests that prove my fix is effective or my feature works
          required: false
