name: Task
description: Create a new task
title: "[Task]: "

body:
  - type: textarea
    id: description
    attributes:
      label: Description (optional)
      description: Add more description if needed
      placeholder: |
        - Backend is bugging out (like usual) because of example1
        - Frontend is not being routed properly
    validations:
      required: false
