name: "🔀 Pull Request"
description: "Enkel PR for kodeendringer"

body:
  - type: input
    id: issue
    attributes:
      label: "Issue #"
      description: "Hvilken Task hører denne PR-en til?"
      placeholder: "#123"
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Hva er gjort?"
      description: "Kort oppsummering av endringen"
      placeholder: |
        - Lagt til validering i registreringsskjema
        - Refaktorert AuthService
    validations:
      required: true

  - type: dropdown
    id: story_points
    attributes:
      label: "Brukte story points (timer)"
      description: "Hvor mange timer brukte du? 1 story point = 1 time"
      options:
        - "1"
        - "2"
        - "3"
        - "5"
        - "8"
        - "13"
        - "20+"
    validations:
      required: true
