name: Backend CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:  
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Format code with Google Java Format
        uses: axel-op/googlejavaformat-action@v4
        with:
          commit-message: "refactor: format code with google-java-format"

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests with JaCoCo
        run: mvn test jacoco:report

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: jacoco-report
          path: backend/target/site/jacoco/
