name: CI/CD Pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    build-backend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'
            - name: Build with Maven
              run: |
                  cd backend
                  mvn --batch-mode --errors --fail-at-end --show-version clean compile

    test-backend:
        runs-on: ubuntu-latest
        needs: build-backend
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'
            - name: Test with Maven
              run: |
                  cd backend
                  mvn --batch-mode --errors --fail-at-end --show-version test -Dspring.profiles.active=test

    package-backend:
        runs-on: ubuntu-latest
        needs: test-backend
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'maven'
            - name: Package with Maven
              run: |
                  cd backend
                  mvn --batch-mode --errors --fail-at-end --show-version package -DskipTests

    build-frontend:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: '10.8.0'
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                      frontend/node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
            - name: Install and build frontend
              run: |
                  cd frontend
                  rm -rf dist node_modules
                  pnpm install --frozen-lockfile
                  pnpm run build

    lint-frontend:
        runs-on: ubuntu-latest
        needs: build-frontend
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: '10.8.0'
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                      frontend/node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
            - name: Run lint
              run: |
                  cd frontend
                  rm -rf dist node_modules
                  pnpm install --frozen-lockfile
                  pnpm run lint

    test-frontend:
        runs-on: ubuntu-latest
        needs: build-frontend
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: '10.8.0'
            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                      frontend/node_modules
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-
            - name: Run tests
              run: |
                  cd frontend
                  rm -rf dist node_modules
                  pnpm install --frozen-lockfile
                  pnpm vitest run
