name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Clean Maven cache
        run: |
          rm -rf ~/.m2/repository
          rm -rf backend/target

      - name: Set up JDK 21
        uses: actions/setup-java@v3.14.1
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Format code with Google Java Format ✨
        uses: axel-op/googlejavaformat-action@v4
        with:
          args: --replace
          files: backend/**/*.java
          commit-message: "refactor: format Java code with google-java-format"

      - name: Verify with maven and generate coverage report
        env:
          TEST_TURNSTILE_SECRET_KEY: ${{ secrets.TEST_TURNSTILE_SECRET_KEY }}
        run: |
          cd backend
          touch .env
          mvn -Dspring.profiles.active=test clean verify jacoco:report

      - name: Upload JaCoCo coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: backend/target/site/jacoco/
          retention-days: 7

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Clean frontend artifacts
        run: |
          rm -rf frontend/node_modules
          rm -rf frontend/dist

      - name: Set up Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: "22"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: "10.8.0"

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install --force --no-cache

      - name: Build frontend
        run: |
          cd frontend
          pnpm run build

      - name: Run lint
        run: |
          cd frontend
          rm -rf frontend/cypress.config.d.ts
          rm -rf frontend/vitest.config.d.ts
          pnpm run lint --no-cache

      - name: Run tests
        run: |
          cd frontend
          pnpm vitest run
