name: Daily Velocity Chart Update

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Optional: Allow manual trigger
  workflow_dispatch:

jobs:
  update-velocity-chart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib numpy requests
    
    - name: Generate velocity chart
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        python velocity_chart.py
      
    - name: Upload velocity chart as artifact
      uses: actions/upload-artifact@v3
      with:
        name: velocity-chart
        path: velocity_chart.png
        retention-days: 90

    - name: Upload CSV data as artifact
      uses: actions/upload-artifact@v3
      with:
        name: issues-data
        path: issues_with_story_points.csv
        retention-days: 90
